name: Deployment pipeline

on:
  push:
    branches: [master, main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3001
      - name: deploy
        if: github.event_name == 'push' && !(contains(github.event.commits.*.message, '#skip')) # Means merge or push to master
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "radiant-woodland-63378" #Must be unique in Heroku
          heroku_email: "ookooko@gmail.com"
          # next 3 lines could be commented for health check test (???)
          healthcheck: "https://radiant-woodland-63378.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: github.event_name == 'push' && !(contains(github.event.commits.*.message, '#skip'))  # Means merge or push to master (and no #skip)
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master, main